Update de.json
winks-vtt/yze-coriolis pull request #254
Opened 2024-03-17 17:37 UTC by MasterZelgadis

Changed judge and dancer to the female version in german

2024-03-17 17:52 UTC, IrishWolf requested changes
Die Änderung zur Richterin ist korrekt, aber laut Regelwerk ist der Tänzer männlich.
Quelle: Grundregelwerk Seite 233
![image](https://github.com/winks-vtt/yze-coriolis/assets/36819852/89c75f79-aa30-492f-ab6d-980a0f4362bc)

The change for the Richterin (the judge) is correct but the Tänzer (dancer) is male.
Source: CRB p. 233

2024-03-17 17:59 UTC, MasterZelgadis commented
Yep, correct. Don't know where I saw the female version of the dancer.. 
Maybe you could correct another one with this, "Kybern**i**tische Implantate" -> "Kybern**e**tische Implantate", so I don't have to make another PR

2024-03-17 18:14 UTC, IrishWolf approved these changes

2024-03-27 11:50 UTC, merged

2024-03-27 11:52 UTC, AlexOkafor commented
Thank you!